export const yogaClass = [
    {
        _id: "65d5e21527e6fd45d7589cdd",
        name: "Sunrise Yoga",
        level: "beginner",
        instructor: "John Doe",
        organization: "Yoga Wellness",
        startTime: "6:00 AM",
        endTime: "7:00 AM",
        duration: 60,
        frequency: ["Monday", "Wednesday", "Friday"],
        healthCondition: "Good health",
        style: "Hatha",
        price: 10,
        rating: 4.5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOB0e7Lz-Y_WGXwM6MABjGguXxZANve2FolQ&usqp=CAU",
        __v: 0,
    },
    {
        _id: "65d5e25027e6fd45d7589cdf",
        name: "Sunrise Yoga",
        level: "beginner",
        instructor: "John Doe",
        organization: "Yoga Wellness",
        startTime: "9:00 AM",
        endTime: "10:00 AM",
        duration: 60,
        frequency: ["Tuesday", "Thursday"],
        healthCondition: "Good health",
        style: "Hatha",
        price: 10,
        rating: 4.5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOB0e7Lz-Y_WGXwM6MABjGguXxZANve2FolQ&usqp=CAU",
        __v: 0,
    },
    {
        _id: "65d5e29827e6fd45d7589ce1",
        name: "Sunrise Yoga",
        level: "beginner",
        instructor: "John Doe",
        organization: "Yoga Wellness",
        startTime: "4:00 PM",
        endTime: "5:00 PM",
        duration: 60,
        frequency: ["Saturday"],
        healthCondition: "Good health",
        style: "Hatha",
        price: 10,
        rating: 4.5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOB0e7Lz-Y_WGXwM6MABjGguXxZANve2FolQ&usqp=CAU",
        __v: 0,
    },
];
